services:
  mongo:
    image: mongo
    container_name: mongodb
    command: --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ttn
      MONGO_INITDB_ROOT_PASSWORD: ng26072005
    
  mongo-express:
    image: mongo-express
    container_name: mongo-exp
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ttn
      ME_CONFIG_MONGODB_ADMINPASSWORD: ng26072005
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin 
      ME_CONFIG_BASICAUTH_USERNAME: admin    
      ME_CONFIG_BASICAUTH_PASSWORD: admin123   
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  
  mysql:
    image: mysql
    container_name: mysql-tnchat
    environment:
      MYSQL_DATABASE: tnchat
      MYSQL_ROOT_PASSWORD: Nguyen26072005.
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mongo: {}
  mysql: {}